/**
 * CityFlow Simulation Engine
 *
 * Pure, deterministic functions that turn the Bengaluru dataset
 * (src/data/generated/bengaluruDataset.json, built by scripts/dataset/build_dataset.py)
 * and a what-if scenario into per-zone and city-wide pressure indices.
 *
 * Every pressure index is a utilisation percentage: 100 means demand equals capacity.
 *   traffic   = peak-direction PCU-km demand / arterial-network PCU-km capacity
 *   logistics = freight fleet utilisation, stretched by congestion
 *   waste     = waste generated / allocated processing capacity, stretched by congestion
 * See ARCHITECTURE.md for the derivation of each input.
 */

export const PRIVATE_MODES = ['twoWheeler', 'carVan', 'auto', 'taxi'];

export const SCENARIO_DEFAULTS = {
  privateVehicleModifier: 1.0,
  publicTransitModifier: 1.0,
  deliveryFreightModifier: 1.0,
  closedCorridorId: null
};

function assumption(dataset, key) {
  return dataset.constants.assumptions[key].value;
}

export function sanitizeScenario(scenario = {}) {
  const num = (v, d) => (typeof v === 'number' && Number.isFinite(v) ? v : d);
  return {
    privateVehicleModifier: num(scenario.privateVehicleModifier, 1.0),
    publicTransitModifier: num(scenario.publicTransitModifier, 1.0),
    deliveryFreightModifier: num(scenario.deliveryFreightModifier, 1.0),
    closedCorridorId: scenario.closedCorridorId || null
  };
}

/**
 * Daily resident trips by private mode after the transit-service change and the
 * private-vehicle modifier. Riders gained or lost by transit move to or from the
 * private modes in proportion to their existing shares.
 */
export function calculateZoneTrips(zone, dataset, scenario) {
  const { dailyTrips, modeShares } = zone.mobility;
  const elasticity = assumption(dataset, 'transitServiceElasticity');

  const basePt = dailyTrips * modeShares.publicTransport;
  const basePrivate = Object.fromEntries(PRIVATE_MODES.map((m) => [m, dailyTrips * modeShares[m]]));
  const privateTotal = PRIVATE_MODES.reduce((s, m) => s + basePrivate[m], 0);

  // Positive = riders gained by transit. Cannot lose more riders than exist or gain more than drive today.
  const rawShift = basePt * elasticity * (scenario.publicTransitModifier - 1);
  const ptShift = Math.max(-basePt, Math.min(privateTotal, rawShift));

  const privateTrips = {};
  for (const m of PRIVATE_MODES) {
    const share = privateTotal > 0 ? basePrivate[m] / privateTotal : 0;
    privateTrips[m] = Math.max(0, basePrivate[m] - ptShift * share) * scenario.privateVehicleModifier;
  }

  return { ptTrips: basePt + ptShift, ptShift, privateTrips };
}

/** Peak-hour vehicles and PCU-km generated by a zone's residents. */
export function calculateResidentPeakLoad(zone, trips, dataset) {
  const { occupancy, pcu } = dataset.constants;
  const phf = assumption(dataset, 'peakHourFactor');
  const tripLength = zone.mobility.averageTripLengthKm;

  const peakVehicles = {};
  let pcuKm = 0;
  for (const m of PRIVATE_MODES) {
    peakVehicles[m] = (trips.privateTrips[m] * phf) / occupancy[m];
    pcuKm += peakVehicles[m] * pcu[m] * tripLength;
  }
  return { peakVehicles, pcuKm };
}

/** Arterial-network capacity after any corridor closure. */
export function calculateEffectiveCapacity(zone, dataset, closedCorridorId) {
  const base = zone.roads.majorCapacityPcuKmPerHr;
  const corridor = closedCorridorId ? dataset.corridors.find((c) => c.id === closedCorridorId) : null;
  const lost = corridor?.zones?.[zone.id] ?? 0;
  return { capacity: Math.max(1, base - lost), lostCapacity: lost };
}

/** Travel-time index from the calibrated delay curve: 1 + alpha * (V/C)^beta. */
export function travelTimeIndex(vc, dataset) {
  const alpha = dataset.constants.calibration.bprAlpha;
  const beta = assumption(dataset, 'bprBeta');
  return 1 + alpha * Math.pow(Math.max(0, vc), beta);
}

/**
 * Congestion stretch on delivery / collection cycles, relative to the city-average
 * baseline congestion the fleets are sized for. Only the driving share of a cycle stretches.
 */
export function cycleTimeFactor(tti, dataset) {
  const s = assumption(dataset, 'travelShareOfCycleTime');
  const reference = dataset.constants.calibration.targetTravelTimeIndex;
  return (1 - s) + s * (tti / reference);
}

export function calculateOverallPressure(traffic, logistics, waste, dataset) {
  const w = assumption(dataset, 'overallWeights');
  return w.traffic * traffic + w.logistics * logistics + w.waste * waste;
}

const round1 = (v) => Number(v.toFixed(1));

/** Main entry point: full simulation for every zone plus a city summary. */
export function calculateCitySimulation(dataset, rawScenario = {}) {
  const scenario = sanitizeScenario(rawScenario);
  const split = assumption(dataset, 'tripEndSplit');
  const majorShare = assumption(dataset, 'majorRoadVehicleKmShare');
  const directional = assumption(dataset, 'peakDirectionShare') / 0.5;
  const freeFlow = assumption(dataset, 'freeFlowSpeedKmph');
  const fleetUtilisation = assumption(dataset, 'freightFleetUtilisation');

  // Pass 1: resident-generated load (needed city-wide for the attraction half of trip ends)
  const pass1 = dataset.zones.map((zone) => {
    const trips = calculateZoneTrips(zone, dataset, scenario);
    return { zone, trips, resident: calculateResidentPeakLoad(zone, trips, dataset) };
  });
  const cityResidentPcuKm = pass1.reduce((s, p) => s + p.resident.pcuKm, 0);

  // Pass 2: zone demand, capacity and pressures
  const zones = pass1.map(({ zone, trips, resident }) => {
    const privatePcuKm = split * resident.pcuKm + (1 - split) * cityResidentPcuKm * zone.demographics.jobsShare;
    const busPcuKm = zone.transit.busPeakPcuKmPerHr * scenario.publicTransitModifier;
    const goodsPcuKm = zone.freight.goodsPeakPcuKmPerHr * scenario.deliveryFreightModifier;
    const totalPcuKm = privatePcuKm + busPcuKm + goodsPcuKm;
    const peakDirectionDemand = totalPcuKm * majorShare * directional;

    const { capacity, lostCapacity } = calculateEffectiveCapacity(zone, dataset, scenario.closedCorridorId);
    const vc = peakDirectionDemand / capacity;
    const tti = travelTimeIndex(vc, dataset);
    const cycle = cycleTimeFactor(tti, dataset);

    const trafficPressure = vc * 100;
    const logisticsPressure = fleetUtilisation * scenario.deliveryFreightModifier * cycle * 100;
    const wastePressure = (zone.waste.generationTpd / zone.waste.processingCapacityTpd) * cycle * 100;
    const overallPressure = calculateOverallPressure(trafficPressure, logisticsPressure, wastePressure, dataset);

    return {
      id: zone.id,
      name: zone.name,
      center: zone.center,
      polygon: zone.polygon,
      source: zone,
      // Pressure indices (utilisation %, 100 = at capacity)
      trafficPressure: round1(trafficPressure),
      logisticsPressure: round1(logisticsPressure),
      wastePressure: round1(wastePressure),
      overallPressure: round1(overallPressure),
      // Traffic internals
      peakVehicles: Object.fromEntries(Object.entries(resident.peakVehicles).map(([k, v]) => [k, Math.round(v)])),
      demandPcuKmPerHr: Math.round(peakDirectionDemand),
      totalPcuKmPerHr: Math.round(totalPcuKm),
      capacityPcuKmPerHr: Math.round(capacity),
      lostCapacityPcuKmPerHr: Math.round(lostCapacity),
      volumeCapacityRatio: Number(vc.toFixed(2)),
      travelTimeIndex: Number(tti.toFixed(2)),
      peakSpeedKmph: round1(freeFlow / tti),
      // Transit
      ptDailyTrips: Math.round(trips.ptTrips),
      ptShiftTrips: Math.round(trips.ptShift),
      // Freight and waste
      freightDemandTpd: Math.round(zone.freight.freightDemandTpd * scenario.deliveryFreightModifier),
      goodsPeakVehicles: Math.round(zone.freight.goodsPeakVehicles * scenario.deliveryFreightModifier),
      wasteGenerationTpd: zone.waste.generationTpd,
      wasteProcessingCapacityTpd: zone.waste.processingCapacityTpd,
      cycleTimeFactor: Number(cycle.toFixed(2)),
      isCorridorClosed: lostCapacity > 0
    };
  });

  return { zones, citySummary: calculateCitySummary(zones, dataset), scenario };
}

/** City-wide indices, weighted by where the load is rather than averaged across zones. */
export function calculateCitySummary(zones = [], dataset) {
  if (!zones.length) {
    return { trafficPressure: 0, logisticsPressure: 0, wastePressure: 0, overallPressure: 0, peakSpeedKmph: 0 };
  }
  const sum = (f) => zones.reduce((s, z) => s + f(z), 0);

  // V/C as experienced by traffic: weighted by vehicle-km, so a gridlocked core is not averaged away by empty outskirts
  const traffic = sum((z) => z.trafficPressure * z.demandPcuKmPerHr) / sum((z) => z.demandPcuKmPerHr);
  const freight = sum((z) => z.freightDemandTpd);
  const logistics = freight > 0 ? sum((z) => z.logisticsPressure * z.freightDemandTpd) / freight : 0;
  const waste = (sum((z) => z.wasteGenerationTpd * z.cycleTimeFactor) / sum((z) => z.wasteProcessingCapacityTpd)) * 100;
  // Harmonic mean speed weighted by vehicle-km, i.e. total distance / total time
  const speed = sum((z) => z.totalPcuKmPerHr) / sum((z) => z.totalPcuKmPerHr / z.peakSpeedKmph);

  return {
    trafficPressure: round1(traffic),
    logisticsPressure: round1(logistics),
    wastePressure: round1(waste),
    overallPressure: round1(calculateOverallPressure(traffic, logistics, waste, dataset)),
    peakSpeedKmph: round1(speed)
  };
}
