import React from 'react';
import { CITY_DATASET } from '../data/cityData';
import { calibrateAlpha, calibrateGravityBeta } from '../engine/simulationEngine';

function formatValue(value) {
  if (typeof value === 'object') {
    return Object.entries(value).map(([k, v]) => `${k} ${v}`).join(', ');
  }
  return String(value);
}

export default function DataProvenance() {
  const { meta, constants } = CITY_DATASET;
  const { calibration, assumptions } = constants;

  return (
    <section aria-labelledby="provenance-heading" className="panel data-provenance-panel">
      <div className="provenance-header">
        <div>
          <h2 id="provenance-heading" className="provenance-title">Data sources and assumptions</h2>
          <span className="provenance-source">Generated by {meta.generatedBy}</span>
        </div>
        <span className="badge badge-info">Base year {meta.baseYear}</span>
      </div>

      <p className="provenance-description">
        Two parameters are fitted, both by the engine at start-up. The delay-curve coefficient (α = {calibrateAlpha(CITY_DATASET).toFixed(2)})
        is solved so the simulated city-wide peak travel-time index equals {calibration.targetTravelTimeIndex}, the ratio of free-flow
        speed to the {constants.observedPeakSpeedKmph.private} km/h peak speed observed in the CMP 2020 speed survey. The gravity
        model's distance decay (β = {calibrateGravityBeta(CITY_DATASET).toFixed(3)} per km) is solved so the mean modelled trip
        matches the CMP 2020 trip lengths by mode. Every figure in the zone inspector is tagged Measured, Derived or Estimated.
      </p>

      <div className="provenance-grid">
        <div className="provenance-card">
          <h3 className="provenance-card-title">Sources</h3>
          <ul className="provenance-list">
            {meta.sources.map((s) => (
              <li key={s.id}>
                <strong>{s.url ? <a href={s.url} target="_blank" rel="noreferrer">{s.name}</a> : s.name}</strong>
                {' '}({s.year})
              </li>
            ))}
          </ul>
        </div>

        <div className="provenance-card">
          <h3 className="provenance-card-title">Assumptions</h3>
          <ul className="provenance-list">
            {Object.entries(assumptions).map(([key, a]) => (
              <li key={key}>
                <strong>{key}: {formatValue(a.value)}</strong> — {a.basis}
              </li>
            ))}
          </ul>
        </div>
      </div>
    </section>
  );
}
